<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

/* promises/src */
include(__DIR__ . '/psr/http-message/src/MessageInterface.php');
include(__DIR__ . '/psr/http-message/src/RequestInterface.php');
include(__DIR__ . '/psr/http-message/src/ResponseInterface.php');
include(__DIR__ . '/psr/http-message/src/ServerRequestInterface.php');
include(__DIR__ . '/psr/http-message/src/StreamInterface.php');
include(__DIR__ . '/psr/http-message/src/UploadedFileInterface.php');
include(__DIR__ . '/psr/http-message/src/UriInterface.php');

/* guzzlehttp/promises/src */
include(__DIR__ . '/guzzlehttp/promises/src/RejectionException.php');
include(__DIR__ . '/guzzlehttp/promises/src/AggregateException.php');
include(__DIR__ . '/guzzlehttp/promises/src/CancellationException.php');
include(__DIR__ . '/guzzlehttp/promises/src/PromiseInterface.php');
include(__DIR__ . '/guzzlehttp/promises/src/PromisorInterface.php');
include(__DIR__ . '/guzzlehttp/promises/src/Coroutine.php');
include(__DIR__ . '/guzzlehttp/promises/src/FulfilledPromise.php');

include(__DIR__ . '/guzzlehttp/promises/src/EachPromise.php');
include(__DIR__ . '/guzzlehttp/promises/src/Promise.php');
include(__DIR__ . '/guzzlehttp/promises/src/RejectedPromise.php');
include(__DIR__ . '/guzzlehttp/promises/src/TaskQueueInterface.php');
include(__DIR__ . '/guzzlehttp/promises/src/TaskQueue.php');

/* guzzlehttp/guzzle/src */
include(__DIR__ . '/guzzlehttp/guzzle/src/ClientInterface.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Client.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/HandlerStack.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/MessageFormatter.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Middleware.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Pool.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/RedirectMiddleware.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/RequestOptions.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/RetryMiddleware.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/TransferStats.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/UriTemplate.php');

/* guzzlehttp/guzzle/src/Handler */
include(__DIR__ . '/guzzlehttp/guzzle/src/Handler/CurlFactoryInterface.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Handler/CurlFactory.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Handler/CurlHandler.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Handler/EasyHandle.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Handler/MockHandler.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Handler/StreamHandler.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Handler/Proxy.php');

/* guzzlehttp/guzzle/src/Exception */
include(__DIR__ . '/guzzlehttp/guzzle/src/Exception/GuzzleException.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Exception/TransferException.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Exception/RequestException.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Exception/BadResponseException.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Exception/ClientException.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Exception/ConnectException.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Exception/SeekException.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Exception/ServerException.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Exception/TooManyRedirectsException.php');

/* guzzlehttp/guzzle/src/Cookie */
include(__DIR__ . '/guzzlehttp/guzzle/src/Cookie/CookieJarInterface.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Cookie/CookieJar.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Cookie/FileCookieJar.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Cookie/SessionCookieJar.php');
include(__DIR__ . '/guzzlehttp/guzzle/src/Cookie/SetCookie.php');

/* guzzlehttp/psr7/src */
include(__DIR__ . '/guzzlehttp/psr7/src/StreamDecoratorTrait.php');

include(__DIR__ . '/guzzlehttp/psr7/src/AppendStream.php');
include(__DIR__ . '/guzzlehttp/psr7/src/BufferStream.php');
include(__DIR__ . '/guzzlehttp/psr7/src/CachingStream.php');
include(__DIR__ . '/guzzlehttp/psr7/src/DroppingStream.php');
include(__DIR__ . '/guzzlehttp/psr7/src/FnStream.php');
include(__DIR__ . '/guzzlehttp/psr7/src/InflateStream.php');
include(__DIR__ . '/guzzlehttp/psr7/src/LazyOpenStream.php');
include(__DIR__ . '/guzzlehttp/psr7/src/LimitStream.php');
include(__DIR__ . '/guzzlehttp/psr7/src/MessageTrait.php');
include(__DIR__ . '/guzzlehttp/psr7/src/MultipartStream.php');
include(__DIR__ . '/guzzlehttp/psr7/src/NoSeekStream.php');
include(__DIR__ . '/guzzlehttp/psr7/src/PumpStream.php');
include(__DIR__ . '/guzzlehttp/psr7/src/Request.php');
include(__DIR__ . '/guzzlehttp/psr7/src/Response.php');
include(__DIR__ . '/guzzlehttp/psr7/src/Stream.php');
include(__DIR__ . '/guzzlehttp/psr7/src/StreamWrapper.php');
include(__DIR__ . '/guzzlehttp/psr7/src/UploadedFile.php');
include(__DIR__ . '/guzzlehttp/psr7/src/Uri.php');
include(__DIR__ . '/guzzlehttp/psr7/src/UriNormalizer.php');
include(__DIR__ . '/guzzlehttp/psr7/src/UriResolver.php');

return ComposerAutoloaderInit8522e7a64c975fd37b3d0d794652cde5::getLoader();
